Match User omni-monitor-tunnel
    AuthenticationMethods publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    AllowTcpForwarding remote
    PermitListen none
    AllowStreamLocalForwarding remote
    StreamLocalBindUnlink yes
    StreamLocalBindMask 0117
    PermitTTY no
    LogLevel INFO
    ClientAliveInterval 20
    ClientAliveCountMax 3
    MaxSessions 0
    PermitUserRC no
    X11Forwarding no
    AllowAgentForwarding no
    PermitTunnel no
    ForceCommand /usr/sbin/nologin
Match all
